fix(git1.7): ensure errors aren't raised in level initialization
On the `push`, `push_branch` and `fetch` levels the following error was
displayed in the terminal on initialization:

    error: unknown switch `u'
    usage: git branch [options] [-r | -a] [--merged | --no-merged]
       or: git branch [options] [-l] [-f] <branchname> [<start-point>]
       or: git branch [options] [-r] (-d | -D) <branchname>
       or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

This warning is a result of the -u flag not being available in previous
versions of git. The level solution is not affected by this so the
warning is piped to /dev/null

This closes #161